name: porto-frontend
image:
  tag: v1.0.0
  name: porto_frontend
  registry: maratonaaks.azurecr.io
appPort: 80

deployment:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  hostName: porto-frontend.67adafcf87fe4e9abac2.eastus.aksapp.io

service:
  port:

configMap:
  name: frontend-config
  backendUrl: http://porto-backend.67adafcf87fe4e9abac2.eastus.aksapp.io
